package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'VCSAPIDocs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("VCSAPIDocs")) {
    val expected = GitVcsRoot({
        id("VCSAPIDocs")
        name = "API Docs"
        url = "https://github.com/ktorio/api.ktor.io.git"
        userNameStyle = GitVcsRoot.UserNameStyle.NAME
        authMethod = password {
            userName = "hhariri"
            password = "credentialsJSON:a48648d8-f9b1-4720-bef0-85445fe9171f"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "hhariri"
            password = "credentialsJSON:8d94d67f-dbc2-4349-80d0-edfab8a652c3"
        }
    }

}
